//
//  SkinLesionRecord.swift
//  Sunny
//
//  Created by Josh Bourke on 13/2/2026.
//


import Foundation

/// The top-level record for a single skin tracking entry.
struct SkinLesionRecord: Codable, Identifiable, Hashable {
    /// A unique identifier for the record (e.g., UUID string).
    /// Essential for SwiftUI Lists and database integrity.
    let id: String 
    
    /// The absolute or relative path to the image file.
    let imagePath: String
    
    /// The timestamp when the analysis was performed (Format: YYYY-MM-DD HH:MM:SS).
    let timestamp: String
    
    /// The morphological description generated by the VLM.
    let analysis: SkinAnalysis
    
    /// The time taken by the VLM to process the image.
    let latency: String?

    enum CodingKeys: String, CodingKey {
        case id
        case imagePath = "image_path"
        case timestamp
        case analysis
        case latency
    }
}

/// The descriptive morphological components of the skin lesion.
struct SkinAnalysis: Codable, Hashable {
    /// Description of the lesion type (e.g., "A pigmented macule").
    let lesionType: String
    
    /// Description of hues and pigment distribution.
    let color: String
    
    /// Description of the balance of shape and color across the axes.
    let symmetry: String
    
    /// Description of the edges (e.g., notched, blurry, or distinct).
    let borders: String
    
    /// Description of the physical surface quality (e.g., smooth, scaly).
    let texture: String
    
    /// A 1-2 sentence plain-English summary for the user to share with a doctor.
    let summary: String

    enum CodingKeys: String, CodingKey {
        case lesionType = "lesion_type"
        case color
        case symmetry
        case borders
        case texture
        case summary
    }
}

// MARK: - Extensions
extension SkinLesionRecord {
    /// Computed property to convert the timestamp string into a Swift Date object.
    var date: Date? {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        return formatter.date(from: timestamp)
    }
}